<a href="https://colab.research.google.com/github/Kaiziferr/NLP_Workshop/blob/master/embedding/01_workshop_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El presente proyecto tiene como finalidad el desarrollo de la incrustración de palabras con keras, a travez de un ejercicio de análisis de sentimiento basico. El tutorial fue tomado de https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [1]:
import numpy as np

from keras.models import Sequential
from keras.preprocessing import text, sequence
from keras.layers import Dense, Flatten, Embedding

In [2]:
docs = ['¡Bien hecho!', 'Buen trabajo', 'Gran esfuerzo', 'Buen trabajo','¡Excelente!',
'Débil','¡Esfuerzo pobre!','no es bueno','trabajo pobre', 'Podría haberlo hecho mejor.']
labels = np.array([1,1,1,1,1,0,0,0,0,0])

# **Encoder**
---



In [3]:
# Definir el vocabulario = 50
vocab_size = 50

encoded = [text.one_hot(d, vocab_size) for d in docs]
print("Se definio un vocabulario de 50 para reducir el número de colisiones")
encoded

Se definio un vocabulario de 50 para reducir el número de colisiones


[[31, 8],
 [18, 38],
 [5, 26],
 [18, 38],
 [28],
 [28],
 [31, 34],
 [48, 24, 35],
 [38, 34],
 [37, 25, 8, 45]]

# **Pad Secuencia**
---

In [19]:
max_length = 4
padded_docs = sequence.pad_sequences(encoded, maxlen=max_length, padding='post', truncating='pre')
print("Las secuencias tienen diferentes longitudes y Keras prefiere que las entradas estén vectorizadas y\nque todas las entradas tengan la misma longitud.\nRellenaremos todas las secuencias de entrada para que tengan una longitud de 4. ", 
      "\n\nEl parametro padding indica el relleno de cada frase, si es posterioro o pre", padded_docs, '\n')

Las secuencias tienen diferentes longitudes y Keras prefiere que las entradas estén vectorizadas y
que todas las entradas tengan la misma longitud.
Rellenaremos todas las secuencias de entrada para que tengan una longitud de 4.  

El parametro padding indica el relleno de cada frase, si es posterioro o pre [[31  8  0  0]
 [18 38  0  0]
 [ 5 26  0  0]
 [18 38  0  0]
 [28  0  0  0]
 [28  0  0  0]
 [31 34  0  0]
 [48 24 35  0]
 [38 34  0  0]
 [37 25  8 45]] 



# **La capa Embedding y el modelo**
---



In [22]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', metrics = ['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('accuracy: %.2f' % (accuracy*100))
print('loss: %.2f' % (loss*100))

accuracy: 90.00
loss: 21.53
