In [107]:
import tensorflow as tf
import numpy as np

#### Carga la data

In [108]:
# url del corpus, del tutorial
path_data = tf.keras.utils.get_file('NLP-DL-Corpus.txt', 'https://raw.githubusercontent.com/jorditorresBCN/Deep-Learning-Introduccion-practica-con-Keras/master/DeepLearning-Introduccion-practica-con-Keras-PRIMERA-PARTE.txt')
# Abre el texto
text = open(path_data, 'rb').read().decode(encoding='utf-8')
print(f'Longitud del texto:{len(text)} caracteres')

Longitud del texto:203251 caracteres


**El corpues se trbajar a nivel de caracters**

In [109]:
vocab = sorted(set(text))
print(f'El texto esta compuesto de {len(vocab)} caracteres')
print(vocab)

El texto esta compuesto de 92 caracteres
['\n', '\r', ' ', '!', '"', '#', '%', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\xad', 'ÿ', 'Š', '‡', '…']


In [110]:
# Se define un diccionario por caracter
char2idx = {u:i for i,u in enumerate(vocab)}
idx2char = np.array(vocab)

In [111]:
print(char2idx)

{'\n': 0, '\r': 1, ' ': 2, '!': 3, '"': 4, '#': 5, '%': 6, "'": 7, '(': 8, ')': 9, '*': 10, '+': 11, ',': 12, '-': 13, '.': 14, '/': 15, '0': 16, '1': 17, '2': 18, '3': 19, '4': 20, '5': 21, '6': 22, '7': 23, '8': 24, '9': 25, ':': 26, ';': 27, '<': 28, '=': 29, '>': 30, '?': 31, '@': 32, 'A': 33, 'B': 34, 'C': 35, 'D': 36, 'E': 37, 'F': 38, 'G': 39, 'H': 40, 'I': 41, 'J': 42, 'K': 43, 'L': 44, 'M': 45, 'N': 46, 'O': 47, 'P': 48, 'Q': 49, 'R': 50, 'S': 51, 'T': 52, 'U': 53, 'V': 54, 'W': 55, 'X': 56, 'Y': 57, '[': 58, ']': 59, '_': 60, 'a': 61, 'b': 62, 'c': 63, 'd': 64, 'e': 65, 'f': 66, 'g': 67, 'h': 68, 'i': 69, 'j': 70, 'k': 71, 'l': 72, 'm': 73, 'n': 74, 'o': 75, 'p': 76, 'q': 77, 'r': 78, 's': 79, 't': 80, 'u': 81, 'v': 82, 'w': 83, 'x': 84, 'y': 85, 'z': 86, '\xad': 87, 'ÿ': 88, 'Š': 89, '‡': 90, '…': 91}


In [112]:
idx2char

array(['\n', '\r', ' ', '!', '"', '#', '%', "'", '(', ')', '*', '+', ',',
       '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F',
       'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', '[', ']', '_', 'a', 'b', 'c', 'd',
       'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
       'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\xad', 'ÿ', 'Š', '‡',
       '…'], dtype='<U1')

In [113]:
for char, _ in zip (idx2char, range(len(vocab))):
    print(' {:4s}: {:3d},'.format(repr(char), char2idx[char]))

 '\n':   0,
 '\r':   1,
 ' ' :   2,
 '!' :   3,
 '"' :   4,
 '#' :   5,
 '%' :   6,
 "'" :   7,
 '(' :   8,
 ')' :   9,
 '*' :  10,
 '+' :  11,
 ',' :  12,
 '-' :  13,
 '.' :  14,
 '/' :  15,
 '0' :  16,
 '1' :  17,
 '2' :  18,
 '3' :  19,
 '4' :  20,
 '5' :  21,
 '6' :  22,
 '7' :  23,
 '8' :  24,
 '9' :  25,
 ':' :  26,
 ';' :  27,
 '<' :  28,
 '=' :  29,
 '>' :  30,
 '?' :  31,
 '@' :  32,
 'A' :  33,
 'B' :  34,
 'C' :  35,
 'D' :  36,
 'E' :  37,
 'F' :  38,
 'G' :  39,
 'H' :  40,
 'I' :  41,
 'J' :  42,
 'K' :  43,
 'L' :  44,
 'M' :  45,
 'N' :  46,
 'O' :  47,
 'P' :  48,
 'Q' :  49,
 'R' :  50,
 'S' :  51,
 'T' :  52,
 'U' :  53,
 'V' :  54,
 'W' :  55,
 'X' :  56,
 'Y' :  57,
 '[' :  58,
 ']' :  59,
 '_' :  60,
 'a' :  61,
 'b' :  62,
 'c' :  63,
 'd' :  64,
 'e' :  65,
 'f' :  66,
 'g' :  67,
 'h' :  68,
 'i' :  69,
 'j' :  70,
 'k' :  71,
 'l' :  72,
 'm' :  73,
 'n' :  74,
 'o' :  75,
 'p' :  76,
 'q' :  77,
 'r' :  78,
 's' :  79,
 't' :  80,
 'u' :  81,
 'v' :  82,
 'w'

In [114]:
# Obtener los valores numericos
text_as_int = np.array([char2idx[c] for c in text])
text_as_int

array([48, 78, 75, ...,  2,  1,  0])

In [115]:
#Se definen los tensores
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
char_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

# Se reorganizan los conjuntos de datos en bloques (batch)

In [116]:
#Definimos la secuencia
seq_length = 100
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [117]:
sequences

<BatchDataset shapes: (101,), types: tf.int32>

In [118]:
#10 primeras secuencias
for item in sequences.take(10):
    print(item)

tf.Tensor(
[48 78 75 72 75 67 75  1  0 37 74  2 17 25 21 19 12  2 41 79 61 61 63  2
 33 79 69 73 75 82  2 76 81 62 72 69 63 75  2 51 65 67 81 74 64 61  2 38
 81 74 64 61 63 69 75 74 12  2 65 72  2 80 65 78 63 65 78  2 72 69 62 78
 75  2 64 65  2 72 61  2 79 61 67 61  2 64 65  2 72 61  2 38 81 74 64 61
 63 69 75 74  2], shape=(101,), dtype=int32)
tf.Tensor(
[ 8 75  2 65 72  2 64 65 63 69 73 75 80 65 78 63 65 78 75  2 79 65 67 81
 74  2 75 80 78 61 79  2 66 81 65 74 80 65 79 12  2 65 79 80 65  2 65 79
  2 81 74  2 80 65 73 61  2 64 65  2 64 65 62 61 80 65  9 14  2 37 74  2
 51 65 67 81 74 64 61  2 38 81 74 64 61 63 69 75 74  2 61 76 61 78 65 63
 65  2 76 75 78], shape=(101,), dtype=int32)
tf.Tensor(
[ 2 76 78 69 73 65 78 61  2 82 65 86  2 33 78 71 61 64 85  2 36 61 78 65
 72 72 12  2 81 74 75  2 64 65  2 72 75 79  2 76 78 69 74 63 69 76 61 72
 65 79  2 76 65 78 79 75 74 61 70 65 79  2 64 65  2 72 61  2 76 61 78 80
 65  2 66 69 74 61 72  2 64 65  2 72 61  2 79 61 67 61 14  2 37 74  2 79
 

In [119]:
#10 primeras secuencias
for item in sequences.take(10):
    print(repr(''.join(idx2char[item.numpy()])))

'Prologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion '
'(o el decimotercero segun otras fuentes, este es un tema de debate). En Segunda Fundacion aparece por'
' primera vez Arkady Darell, uno de los principales personajes de la parte final de la saga. En su pri'
'mera escena, Arkady, que tiene 14 anos, esta haciendo sus tareas escolares. En concreto, una redaccio'
'n que lleva por titulo ?El Futuro del Plan Sheldon?. Para hacer la redaccion, Arkady esta utilizando '
'un ?transcriptor?,un dispositivo que convierte su voz en palabras escritas. Este tipo de dispositivo,'
' que para Isaac Asimov era ciencia ficcion en 1953, lo tenemos al alcance de la mano en la mayoria de'
' nuestros smartphones, y el Deep Learning es uno de los responsables de que ya tengamos este tipo de '
'aplicaciones, siendo la tecnologia otro de ellos.En la actualidad disponemos de GPUs (Graphics Proces'
'sor Units), que solo cuestan alrededor de 100 euros, que esta

De esta secuencia se obtiene el conjunto de datos de training que contenga tanto los datos de entrada (desde la posición 0 a la 99) como los datos de salida (desde la posición 1 a la 100). Para ello se crea una función que realiza esta tarea y se aplica a todas las secuencias usando el método map( )de la siguiente forma

In [120]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)
dataset   

<MapDataset shapes: ((100,), (100,)), types: (tf.int32, tf.int32)>

100 caracteres del texto original y la segunda su correspondiente salida, también de 100 caracteres.

In [121]:
for input_example, target_example in dataset.take(1):
    print('Input data: ', repr(''.join(idx2char[input_example.numpy()])))
    print('Target data: ', repr(''.join(idx2char[target_example.numpy()])))

Input data:  'Prologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion'
Target data:  'rologo\r\nEn 1953, Isaac Asimov publico Segunda Fundacion, el tercer libro de la saga de la Fundacion '


# En redes neuronales los datos se agrupan en batches antes de pasarlos al modelo.

In [122]:
BATCH_SIZE = 64
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder = True)

In [123]:
dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int32, tf.int32)>

# Crear la red

In [124]:
def buildModel(vocabSize, embeddingDim, rnnUnits, batchSize):
    model = tf.keras.Sequential([tf.keras.layers.Embedding(vocabSize, embeddingDim, batch_input_shape = [batchSize, None]),
                                 tf.keras.layers.LSTM(rnnUnits, return_sequences = True,stateful = True, recurrent_initializer = 'glorot_uniform'),
                                 tf.keras.layers.Dense(vocabSize)])
    return model

In [125]:
vocabSize = len(vocab)
embeddingDim = 256
rnnUnits = 1024

In [126]:
model = buildModel(
    vocabSize = vocabSize,
    embeddingDim = embeddingDim,
    rnnUnits = rnnUnits,
    batchSize = BATCH_SIZE
)

In [127]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (64, None, 256)           23552     
_________________________________________________________________
lstm_1 (LSTM)                (64, None, 1024)          5246976   
_________________________________________________________________
dense_1 (Dense)              (64, None, 92)            94300     
Total params: 5,364,828
Trainable params: 5,364,828
Non-trainable params: 0
_________________________________________________________________


In [128]:
for inputExampleBatch, targetExampleBatch in dataset.take(1):
    print('Input:', inputExampleBatch.shape, "# (batch_size, sequence length)")
    print('Target:', targetExampleBatch.shape, "# (batch_size, sequence length)")

Input: (64, 100) # (batch_size, sequence length)
Target: (64, 100) # (batch_size, sequence length)


In [129]:
for inputExampleBatch, targetExampleBatch in  dataset.take(1):
    exampleBatchPrediction = model(inputExampleBatch)
    print("Prediction: ", exampleBatchPrediction.shape, "# (batch_size, sequence length, vocab size)")

Prediction:  (64, 100, 92) # (batch_size, sequence length, vocab size)


In [130]:
model

# La capa densa de esta red neuronal no tiene una función de activación

ejemploI = tf.random.categorical(example_batch_predictions[0], num_samples=1)

# Entrenamiento del modelo RNN

Definimos la funcion de perdida

In [131]:
def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

El optimizador sera Adam

In [132]:
model.compile(optimizer='adam', loss=loss)

Checkpoints, una técnica de tolerancia de fallos para procesos cuyo tiempo de ejecución es muy largo. La idea es guardar una instantánea del estado del sistema periódicamente para recuperar desde ese punto la ejecución en caso de fallo del sistema. 

In [133]:
import os

In [134]:
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

In [135]:
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix, save_weights_only=True)

# Entrenando el modelo

In [136]:
sasas

NameError: name 'sasas' is not defined

Epochs = 50
history = model.fit(dataset,epochs=Epochs, callbacks = [checkpoint_callback] )

# Generacion de texto

In [141]:
model = buildModel(vocabSize, embeddingDim, rnnUnits, batchSize=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1,None]))

In [143]:
def generateText(model, start_string):
    numGenerate = 500
    inputEvel = [char2idx[s] for s in start_string]
    inputEvel = tf.expand_dims(inputEvel,0)
    
    text_generated = []
    
    temperature = 0.5
    
    model.reset_states()
    
    for i in range(numGenerate):
        predictions = model(input_eval)
        
        predictions = tf.squeeze(predictions, 0)
        
        predictions = tf.random.categorical(predictions, num_samples = 1)[-1, 0].numpy()
        
        input_eval = tf.expand_dims([predicted_id], 0)
        
        text_generated.append(idx2char[predicted_id])
        
    return (start_string + ''.join(text_generated))

In [145]:
print(generateText(model, start_string=u"modelo"))

NameError: name 'num_generate' is not defined